changelog:
  categories:
    - title: Added
      labels:
        - enhancement
    - title: Fixed
      labels:
        - bug
    - title: Changed
      labels:
        - update
    - title: Other changes
      labels:
        - "*"
